flowchart TB
	End(No extension required)
	Yes(Create an extension!)

	S1(Do you plan on improving the utility of<br/>product carbon footprints for their receivers<br/>by disclosing additional information?<br/> <br/>)
	S1 -- yes --> S4
	S1 -- no --> End
	
	S4(Has an equivalent extension<br/> been <i>published</i> already?<br/> <br/>)
	S4 -- no --> S2
	S4-- yes --> End

	S2(Has the carbon footprint<br/> been calculated in accordance with<br/>the Pathfinder Framework?<br/> <br/>)
	S2 -- yes --> S3
	S2 -- no --> End

    S3(Is the additional information<br>related to the<br>product data, particularly<br>emissions data relating to<br/> a product, services related<br/> to a product or processes<br/> related to a product?<br/> <br/>)
	S3 -- yes --> Yes
	S3 -- no --> End
