flowchart TB
	End(No extension)
	Yes(Create an extension!)

	S1(Do you plan on improving the utility of<br/>Product Carbon Footprints for its receivers<br/>by disclosing additional information?<br/> <br/>)
	S1 -- yes --> S4
	S1 -- no --> End
	
	S4(Is there an equivalent<br/><i>published</i> extension already?<br/> <br/>)
	S4 -- no --> S2
	S4-- yes --> End

	S2(Is the carbon footprint<br/> calculated in accordance with<br/>the Pathfinder Framework?<br/> <br/>)
	S2 -- yes --> S3
	S2 -- no --> End

    S3(Is the additional information<br>related to the context of<br>product data, especially<br>emissions data relating to<br/> a product, services related<br/> to a product or processes<br/> related to a product?<br/> <br/>)
	S3 -- yes --> Yes
	S3 -- no --> End
